-- PostgreSQL runtime fixes discovered by real adapter acceptance.
-- Remove PL/pgSQL ambiguity between the preview table column and local snapshot hash variable.

CREATE OR REPLACE FUNCTION ai_prepare_skill_operation(p_school_id uuid,p_task_id uuid,p_node_id varchar,p_skill_key varchar,p_actor_id varchar,p_input jsonb)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE preview_id uuid:=gen_random_uuid(); target jsonb; scope jsonb; view_data jsonb; versions jsonb:='{}'; input_hash varchar(64):=encode(digest(p_input::text,'sha256'),'hex'); computed_snapshot_hash varchar(64); expiry timestamptz:=now()+interval '10 minutes'; wanted integer; found_count integer; conflict_count integer;
BEGIN
 IF NOT EXISTS(SELECT 1 FROM ai_task_runs WHERE id=p_task_id AND school_id=p_school_id) THEN RAISE EXCEPTION 'skill_task_not_found' USING ERRCODE='P0002'; END IF;
 IF NOT EXISTS(SELECT 1 FROM ai_task_nodes WHERE task_id=p_task_id AND id=p_node_id AND school_id=p_school_id) THEN RAISE EXCEPTION 'skill_task_node_not_found' USING ERRCODE='P0002'; END IF;
 IF NOT EXISTS(SELECT 1 FROM skill_versions WHERE skill_key=p_skill_key AND status='published') THEN RAISE EXCEPTION 'skill_version_not_published' USING ERRCODE='P0002'; END IF;
 CASE p_skill_key
 WHEN 'repair.dispatch.commit.v1' THEN
  wanted:=LEAST(GREATEST(COALESCE((p_input->>'count')::integer,1),1),50);
  IF p_input?'assignments' THEN
   WITH requested AS(SELECT x->>'repairId' repair_id,x->>'assigneeId' assignee_id FROM jsonb_array_elements(p_input->'assignments') x)
   SELECT jsonb_build_object('assignments',COALESCE(jsonb_agg(jsonb_build_object('repairId',r.id,'repairVersion',r.version,'assigneeId',u.id,'repairTitle',r.title,'workerName',u.name) ORDER BY r.created_at),'[]')) INTO target
   FROM requested q JOIN repair_orders r ON r.id=q.repair_id AND r.school_id=p_school_id AND NOT r.is_deleted AND upper(r.status)='PENDING'
   JOIN users u ON u.id=q.assignee_id AND u.school_id=p_school_id AND u.role='repairman' AND u.status='active' AND NOT u.is_deleted;
   wanted:=jsonb_array_length(p_input->'assignments');
  ELSIF p_input?'repairId' THEN
   SELECT jsonb_build_object('assignments',jsonb_build_array(jsonb_build_object('repairId',r.id,'repairVersion',r.version,'assigneeId',u.id,'repairTitle',r.title,'workerName',u.name))) INTO target
   FROM repair_orders r JOIN users u ON u.id=p_input->>'assigneeId' AND u.school_id=p_school_id AND u.role='repairman' AND u.status='active' AND NOT u.is_deleted
   WHERE r.id=p_input->>'repairId' AND r.school_id=p_school_id AND NOT r.is_deleted AND upper(r.status)='PENDING'; wanted:=1;
  ELSE
   WITH repairs AS(SELECT r.*,row_number() OVER(ORDER BY CASE lower(COALESCE(r.priority,'normal')) WHEN 'urgent' THEN 1 WHEN 'high' THEN 2 ELSE 3 END,r.created_at,r.id) seq FROM repair_orders r WHERE r.school_id=p_school_id AND NOT r.is_deleted AND upper(r.status)='PENDING' LIMIT wanted),
   workers AS(SELECT u.id,u.name,row_number() OVER(ORDER BY(SELECT count(*) FROM repair_orders w WHERE w.school_id=p_school_id AND w.assignee_id=u.id AND upper(w.status) IN('DISPATCHED','PROCESSING')),u.id) seq,count(*) OVER() total FROM users u WHERE u.school_id=p_school_id AND u.role='repairman' AND u.status='active' AND NOT u.is_deleted)
   SELECT jsonb_build_object('assignments',COALESCE(jsonb_agg(jsonb_build_object('repairId',r.id,'repairVersion',r.version,'assigneeId',w.id,'repairTitle',r.title,'workerName',w.name) ORDER BY r.seq),'[]')) INTO target FROM repairs r JOIN workers w ON w.seq=((r.seq-1)%w.total)+1;
  END IF;
  found_count:=COALESCE(jsonb_array_length(target->'assignments'),0); IF target IS NULL OR found_count<>wanted THEN RAISE EXCEPTION 'repair_dispatch_targets_or_workers_unavailable' USING ERRCODE='P0002'; END IF;
  SELECT COALESCE(jsonb_object_agg(x->>'repairId',(x->>'repairVersion')::integer),'{}') INTO versions FROM jsonb_array_elements(target->'assignments') x;
  SELECT jsonb_strip_nulls(jsonb_build_object('schoolId',p_school_id,'organizationId',((array_agg(r.organization_id) FILTER(WHERE r.organization_id IS NOT NULL))[1])::text,'buildingId',((array_agg(r.building_id) FILTER(WHERE r.building_id IS NOT NULL))[1])::text)) INTO scope FROM repair_orders r WHERE r.id IN(SELECT x->>'repairId' FROM jsonb_array_elements(target->'assignments') x);
  view_data:=jsonb_build_object('targetCount',found_count,'affectedResources',target->'assignments','stateChanges',jsonb_build_object('from','PENDING','to','DISPATCHED'),'warnings','[]'::jsonb,'outboxEvents',jsonb_build_array('repair.dispatched','repair.sla.started','notification.delivery.requested'));
 WHEN 'notification.publish.commit.v1' THEN
  SELECT count(DISTINCT u.id) INTO found_count FROM users u WHERE u.school_id=p_school_id AND u.status='active' AND NOT u.is_deleted AND (u.role IN(SELECT jsonb_array_elements_text(COALESCE(p_input#>'{audience,roles}','[]'))) OR u.id IN(SELECT jsonb_array_elements_text(COALESCE(p_input#>'{audience,userIds}','[]'))) OR u.primary_organization_id::text IN(SELECT jsonb_array_elements_text(COALESCE(p_input#>'{audience,organizationIds}','[]'))));
  IF found_count=0 THEN RAISE EXCEPTION 'notification_audience_empty' USING ERRCODE='22023'; END IF;
  target:=jsonb_build_object('audience',p_input->'audience','audienceCount',found_count,'title',p_input->>'title','contentHash',encode(digest(p_input->>'content','sha256'),'hex'));
  scope:=jsonb_build_object('schoolId',p_school_id); IF jsonb_array_length(COALESCE(p_input#>'{audience,organizationIds}','[]'))=1 THEN scope:=scope||jsonb_build_object('organizationId',p_input#>>'{audience,organizationIds,0}'); END IF;
  view_data:=jsonb_build_object('targetCount',found_count,'affectedResources',p_input->'audience','stateChanges',jsonb_build_object('from','DRAFT','to',CASE WHEN p_input?'scheduledAt' THEN 'SCHEDULED' ELSE 'PUBLISHED' END),'channels',p_input->'channels','deliveryCost',jsonb_build_object('kind','estimate_units','units',found_count*jsonb_array_length(p_input->'channels')),'warnings',CASE WHEN p_input->>'content'~*'(password|id card|bank card)' THEN jsonb_build_array('sensitive_content_detected') ELSE '[]'::jsonb END);
 WHEN 'classroom.booking.commit.v1' THEN
  SELECT jsonb_build_object('classroomId',c.id,'version',c.version,'name',c.full_name,'capacity',c.capacity,'status',c.status,'startsAt',p_input->>'startsAt','endsAt',p_input->>'endsAt') INTO target FROM classrooms c WHERE c.id=p_input->>'classroomId' AND c.school_id=p_school_id AND lower(c.status)='available';
  IF target IS NULL THEN RAISE EXCEPTION 'classroom_not_available' USING ERRCODE='P0002'; END IF; IF (target->>'capacity')::integer<(p_input->>'attendeeCount')::integer THEN RAISE EXCEPTION 'classroom_capacity_exceeded' USING ERRCODE='22023'; END IF;
  SELECT(SELECT count(*) FROM classroom_bookings b WHERE b.school_id=p_school_id AND b.classroom_id=p_input->>'classroomId' AND upper(b.status) IN('PENDING','APPROVED') AND b.starts_at<(p_input->>'endsAt')::timestamptz AND b.ends_at>(p_input->>'startsAt')::timestamptz)+(SELECT count(*) FROM class_schedules s WHERE s.school_id=p_school_id AND s.classroom_id=p_input->>'classroomId' AND s.status='active' AND s.starts_at<(p_input->>'endsAt')::timestamptz AND s.ends_at>(p_input->>'startsAt')::timestamptz) INTO conflict_count;
  IF conflict_count>0 THEN RAISE EXCEPTION 'classroom_booking_conflict' USING ERRCODE='23P01'; END IF;
  SELECT jsonb_strip_nulls(jsonb_build_object('schoolId',p_school_id,'campusId',campus_id::text,'organizationId',organization_id::text,'buildingId',building_id::text)) INTO scope FROM classrooms WHERE id=p_input->>'classroomId'; versions:=jsonb_build_object(p_input->>'classroomId',(target->>'version')::integer); view_data:=jsonb_build_object('targetCount',1,'affectedResources',jsonb_build_array(target),'stateChanges',jsonb_build_object('booking','CREATE_PENDING'),'conflictCount',0,'warnings','[]'::jsonb);
 WHEN 'lost_found.claim.commit.v1' THEN
  IF NOT COALESCE((p_input->>'humanConfirmed')::boolean,false) THEN RAISE EXCEPTION 'lost_found_human_confirmation_required' USING ERRCODE='42501'; END IF;
  SELECT jsonb_build_object('itemId',i.id,'version',i.version,'itemType',i.item_type,'itemName',i.item_name,'status',i.status,'reporterId',i.reporter_id) INTO target FROM lost_found i WHERE i.id=p_input->>'itemId' AND i.school_id=p_school_id AND lower(i.status) IN('open','matched');
  IF target IS NULL OR NOT EXISTS(SELECT 1 FROM users WHERE id=p_input->>'claimerId' AND school_id=p_school_id AND status='active' AND NOT is_deleted) THEN RAISE EXCEPTION 'lost_found_item_or_claimer_invalid' USING ERRCODE='P0002'; END IF;
  SELECT jsonb_strip_nulls(jsonb_build_object('schoolId',p_school_id,'organizationId',organization_id::text,'ownerUserId',p_input->>'claimerId')) INTO scope FROM lost_found WHERE id=p_input->>'itemId'; versions:=jsonb_build_object(p_input->>'itemId',(target->>'version')::integer); view_data:=jsonb_build_object('targetCount',1,'affectedResources',jsonb_build_array(target- 'reporterId'),'stateChanges',jsonb_build_object('from',target->>'status','to','claimed'),'warnings',jsonb_build_array('human_identity_evidence_required'));
 WHEN 'hygiene.rectification.create.v1' THEN
  SELECT jsonb_build_object('inspectionId',i.id,'version',i.version,'location',i.location,'deterministicScore',i.deterministic_score,'aiAdvisoryScore',i.ai_advisory_score,'status',i.status,'evidenceHash',encode(digest(i.evidence::text,'sha256'),'hex')) INTO target FROM hygiene_inspections i WHERE i.id=p_input->>'inspectionId' AND i.school_id=p_school_id AND i.status IN('COMPLETED','REVIEWED');
  IF target IS NULL OR NOT EXISTS(SELECT 1 FROM users WHERE id=p_input->>'assigneeId' AND school_id=p_school_id AND status='active' AND NOT is_deleted) THEN RAISE EXCEPTION 'hygiene_inspection_or_assignee_invalid' USING ERRCODE='P0002'; END IF;
  SELECT jsonb_strip_nulls(jsonb_build_object('schoolId',p_school_id,'organizationId',organization_id::text,'buildingId',building_id::text,'classId',class_id::text)) INTO scope FROM hygiene_inspections WHERE id=p_input->>'inspectionId'; versions:=jsonb_build_object(p_input->>'inspectionId',(target->>'version')::integer); view_data:=jsonb_build_object('targetCount',1,'affectedResources',jsonb_build_array(target),'stateChanges',jsonb_build_object('rectification','CREATE_OPEN'),'warnings',jsonb_build_array('ai_score_is_advisory_only'));
 WHEN 'dorm_safety.confirm.commit.v1' THEN
  IF NOT COALESCE((p_input->>'onsiteConfirmed')::boolean,false) THEN RAISE EXCEPTION 'dorm_safety_onsite_confirmation_required' USING ERRCODE='42501'; END IF;
  SELECT jsonb_build_object('eventId',e.id,'version',e.version,'eventType',e.event_type,'severity',e.severity,'status',e.status,'observedValue',e.observed_value,'ruleEvidence',e.rule_evidence) INTO target FROM dorm_safety_events e WHERE e.id=p_input->>'eventId' AND e.school_id=p_school_id AND e.status='PENDING_CONFIRMATION';
  IF target IS NULL THEN RAISE EXCEPTION 'dorm_safety_event_not_confirmable' USING ERRCODE='P0002'; END IF; SELECT jsonb_build_object('schoolId',p_school_id,'buildingId',building_id::text) INTO scope FROM dorm_safety_events WHERE id=p_input->>'eventId'; versions:=jsonb_build_object(p_input->>'eventId',(target->>'version')::integer); view_data:=jsonb_build_object('targetCount',1,'affectedResources',jsonb_build_array(target),'stateChanges',jsonb_build_object('from','PENDING_CONFIRMATION','to',upper(p_input->>'outcome')),'warnings',jsonb_build_array('human_onsite_decision','no_punitive_ai_conclusion'));
 WHEN 'visitor.admission.approve.v1' THEN
  SELECT jsonb_build_object('visitorApplicationId',v.id,'version',v.version,'visitorName',v.visitor_name,'purpose',v.purpose,'visitTime',v.visit_time,'status',v.status,'hostId',v.host_id) INTO target FROM visitors v WHERE v.id=p_input->>'visitorApplicationId' AND v.school_id=p_school_id AND upper(v.status)='PENDING'; IF target IS NULL THEN RAISE EXCEPTION 'visitor_application_not_pending' USING ERRCODE='P0002'; END IF;
  IF p_input->>'decision'='approve' AND ((p_input->>'validUntil')::timestamptz<=(p_input->>'validFrom')::timestamptz OR (p_input->>'validUntil')::timestamptz>(p_input->>'validFrom')::timestamptz+interval '12 hours') THEN RAISE EXCEPTION 'visitor_qr_validity_invalid' USING ERRCODE='22023'; END IF;
  SELECT jsonb_strip_nulls(jsonb_build_object('schoolId',p_school_id,'buildingId',building_id::text,'ownerUserId',target->>'hostId')) INTO scope FROM visitors WHERE id=p_input->>'visitorApplicationId'; versions:=jsonb_build_object(p_input->>'visitorApplicationId',(target->>'version')::integer); view_data:=jsonb_build_object('targetCount',1,'affectedResources',jsonb_build_array(target-'hostId'),'stateChanges',jsonb_build_object('from','PENDING','to',upper(p_input->>'decision')),'warnings',CASE WHEN p_input->>'decision'='approve' THEN jsonb_build_array('one_time_qr_will_be_issued') ELSE '[]'::jsonb END);
 WHEN 'maintenance.recommendation.create.v1' THEN
  SELECT count(*) INTO found_count FROM energy_readings r WHERE r.school_id=p_school_id AND r.asset_id=p_input->>'assetId' AND r.quality='valid' AND r.id IN(SELECT value::uuid FROM jsonb_array_elements_text(p_input->'readingIds') value); IF found_count<>jsonb_array_length(p_input->'readingIds') OR found_count<3 THEN RAISE EXCEPTION 'maintenance_real_quality_readings_required' USING ERRCODE='22023'; END IF;
  SELECT jsonb_build_object('assetId',a.id,'version',a.version,'assetCode',a.asset_code,'assetName',a.name,'assetType',a.asset_type,'status',a.status,'readingCount',found_count,'readingIdsHash',encode(digest((p_input->'readingIds')::text,'sha256'),'hex'),'observedFrom',min(r.observed_at),'observedTo',max(r.observed_at),'minimum',min(r.value),'maximum',max(r.value)) INTO target FROM energy_assets a JOIN energy_readings r ON r.asset_id=a.id AND r.school_id=a.school_id WHERE a.id=p_input->>'assetId' AND a.school_id=p_school_id AND a.status='active' AND r.quality='valid' AND r.id IN(SELECT value::uuid FROM jsonb_array_elements_text(p_input->'readingIds') value) GROUP BY a.id;
  IF target IS NULL THEN RAISE EXCEPTION 'maintenance_asset_or_readings_unavailable' USING ERRCODE='P0002'; END IF; SELECT jsonb_strip_nulls(jsonb_build_object('schoolId',p_school_id,'buildingId',building_id::text)) INTO scope FROM energy_assets WHERE id=p_input->>'assetId'; versions:=jsonb_build_object(p_input->>'assetId',(target->>'version')::integer); view_data:=jsonb_build_object('targetCount',1,'affectedResources',jsonb_build_array(target),'stateChanges',jsonb_build_object('recommendation','CREATE_DRAFT'),'warnings',jsonb_build_array('recommendation_is_advisory','no_random_or_synthetic_curve'));
 ELSE RAISE EXCEPTION 'skill_not_bound_to_explicit_domain_adapter' USING ERRCODE='0A000'; END CASE;
 PERFORM ai_assert_skill_binding(p_school_id,p_actor_id,p_skill_key,scope,true); computed_snapshot_hash:=encode(digest(target::text,'sha256'),'hex');
 INSERT INTO skill_operation_previews(id,school_id,task_id,node_id,skill_key,actor_id,input,input_hash,resource_scope,target_snapshot,snapshot_hash,expected_versions,preview,status,expires_at)
 VALUES(preview_id,p_school_id,p_task_id,p_node_id,p_skill_key,p_actor_id,p_input,input_hash,scope,target,computed_snapshot_hash,versions,view_data,'PREPARED',expiry)
 ON CONFLICT(school_id,task_id,node_id,snapshot_hash) DO UPDATE SET input=EXCLUDED.input,input_hash=EXCLUDED.input_hash,preview=EXCLUDED.preview,expected_versions=EXCLUDED.expected_versions,status='PREPARED',expires_at=EXCLUDED.expires_at RETURNING id INTO preview_id;
 INSERT INTO ai_tool_invocations(school_id,task_id,node_id,skill_id,idempotency_key,status,request,response,started_at,completed_at) VALUES(p_school_id,p_task_id,p_node_id,p_skill_key,p_task_id::text||':'||p_node_id||':prepare:'||computed_snapshot_hash,'PREPARED',p_input,jsonb_build_object('previewId',preview_id,'snapshotHash',computed_snapshot_hash),now(),now()) ON CONFLICT(school_id,idempotency_key) DO NOTHING;
 INSERT INTO ai_audit_events(school_id,task_id,node_id,actor_type,actor_id,event_type,metadata) VALUES(p_school_id,p_task_id,p_node_id,'user',p_actor_id,'skill.operation.prepared',jsonb_build_object('skillKey',p_skill_key,'previewId',preview_id,'snapshotHash',computed_snapshot_hash));
 RETURN jsonb_build_object('previewId',preview_id,'skillKey',p_skill_key,'input',p_input,'inputHash',input_hash,'snapshotHash',computed_snapshot_hash,'resourceScope',scope,'targetSnapshot',target,'expectedVersions',versions,'preview',view_data,'expiresAt',expiry);
END $$;

