import { createHash, generateKeyPairSync, randomUUID, sign as cryptoSign, verify as cryptoVerify } from 'node:crypto'
import { mkdir, readFile, rename, unlink, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { getPostgresPool, hasPostgresDatabaseUrl } from '@/storage/database/postgres'
import { UserRole, type User } from '@/types'
import type { FederationContributionView, FederationJobView, FederationNodeView, FederationOverview, MultimodalAssetView, MultimodalModality, MultimodalObservationView, MultimodalOverview } from './federation-types'

const MAX_ASSET_BYTES = 15 * 1024 * 1024
const DEFAULT_MINIMUM_GROUP = 5
const ALLOWED_TYPES: Record<string, { modality: MultimodalModality; extension: string }> = {
  'image/png': { modality: 'IMAGE', extension: '.png' }, 'image/jpeg': { modality: 'IMAGE', extension: '.jpg' }, 'image/gif': { modality: 'IMAGE', extension: '.gif' }, 'image/webp': { modality: 'IMAGE', extension: '.webp' },
  'audio/wav': { modality: 'AUDIO', extension: '.wav' }, 'audio/x-wav': { modality: 'AUDIO', extension: '.wav' }, 'audio/mpeg': { modality: 'AUDIO', extension: '.mp3' }, 'audio/ogg': { modality: 'AUDIO', extension: '.ogg' },
  'video/mp4': { modality: 'VIDEO', extension: '.mp4' }, 'video/webm': { modality: 'VIDEO', extension: '.webm' },
  'text/plain': { modality: 'DOCUMENT', extension: '.txt' }, 'text/markdown': { modality: 'DOCUMENT', extension: '.md' }, 'text/csv': { modality: 'DOCUMENT', extension: '.csv' }, 'application/json': { modality: 'DOCUMENT', extension: '.json' }, 'application/pdf': { modality: 'DOCUMENT', extension: '.pdf' },
}

export class FederationError extends Error {
  constructor(readonly code: 'TENANT_REQUIRED' | 'FORBIDDEN' | 'BACKEND_UNAVAILABLE' | 'INVALID_REQUEST' | 'NOT_FOUND' | 'CONFLICT' | 'STORAGE_FAILURE', message: string) { super(message); this.name = 'FederationError' }
}
function requireOperator(user: User): { schoolId: string } {
  if (!user.school_id) throw new FederationError('TENANT_REQUIRED', '当前身份没有绑定学校租户')
  if (user.role !== UserRole.SUPER_ADMIN && user.role !== UserRole.AI_OPS_ADMIN) throw new FederationError('FORBIDDEN', '只有 AI 系统运维管理员可以管理多模态与联邦节点')
  if (!hasPostgresDatabaseUrl()) throw new FederationError('BACKEND_UNAVAILABLE', '多模态联邦控制面需要 PostgreSQL 审计存储')
  return { schoolId: user.school_id }
}
function object(value: unknown): Record<string, unknown> { return value && typeof value === 'object' && !Array.isArray(value) ? value as Record<string, unknown> : {} }
function iso(value: unknown): string { if (value instanceof Date) return value.toISOString(); return typeof value === 'string' ? value : new Date(0).toISOString() }
function number(value: unknown): number { const parsed = Number(value ?? 0); return Number.isFinite(parsed) ? parsed : 0 }
function sha(value: Buffer | string): string { return createHash('sha256').update(value).digest('hex') }
function runtimeRoot(): string { const configured = process.env.AI_RUNTIME_DATA_DIR?.trim(); return path.resolve(configured ? (path.isAbsolute(configured) ? configured : path.join(process.cwd(), configured)) : path.join(process.cwd(), '.runtime-data')) }
function safePath(...segments: string[]): string { const root = runtimeRoot(); const target = path.resolve(root, ...segments); if (target !== root && !target.startsWith(`${root}${path.sep}`)) throw new FederationError('STORAGE_FAILURE', '对象存储路径越界'); return target }
function safeSegment(value: string): string { return value.replace(/[^a-zA-Z0-9_-]/g, '_').slice(0, 100) }

function inspectImage(buffer: Buffer, contentType: string): Record<string, number | string | boolean> {
  let width = 0, height = 0
  if (contentType === 'image/png' && buffer.length >= 24 && buffer.subarray(0, 8).equals(Buffer.from([137,80,78,71,13,10,26,10]))) { width = buffer.readUInt32BE(16); height = buffer.readUInt32BE(20) }
  else if (contentType === 'image/gif' && buffer.length >= 10 && buffer.subarray(0, 3).toString('ascii') === 'GIF') { width = buffer.readUInt16LE(6); height = buffer.readUInt16LE(8) }
  else if (contentType === 'image/jpeg' && buffer.length > 4 && buffer[0] === 0xff && buffer[1] === 0xd8) { let offset = 2; while (offset + 9 < buffer.length) { if (buffer[offset] !== 0xff) { offset += 1; continue } const marker = buffer[offset + 1]; const length = buffer.readUInt16BE(offset + 2); if ([0xc0,0xc1,0xc2,0xc3,0xc5,0xc6,0xc7,0xc9,0xca,0xcb,0xcd,0xce,0xcf].includes(marker)) { height = buffer.readUInt16BE(offset + 5); width = buffer.readUInt16BE(offset + 7); break } if (length < 2) break; offset += 2 + length } }
  return { width, height, megapixels: Number((width * height / 1_000_000).toFixed(3)), headerVerified: width > 0 && height > 0 }
}
function inspectWav(buffer: Buffer): Record<string, number | string | boolean> { if (buffer.length < 44 || buffer.subarray(0, 4).toString('ascii') !== 'RIFF' || buffer.subarray(8, 12).toString('ascii') !== 'WAVE') return { headerVerified: false }; const channels = buffer.readUInt16LE(22), sampleRate = buffer.readUInt32LE(24), byteRate = buffer.readUInt32LE(28); return { headerVerified: true, channels, sampleRate, durationSeconds: byteRate > 0 ? Number(((buffer.length - 44) / byteRate).toFixed(2)) : 0 } }
function inspectDocument(buffer: Buffer, contentType: string): Record<string, number | string | boolean> { if (contentType === 'application/pdf') { const headerVerified = buffer.subarray(0, 5).toString('ascii') === '%PDF-'; return { headerVerified, pages: (buffer.toString('latin1').match(/\/Type\s*\/Page\b/g) ?? []).length } } const text = buffer.toString('utf8'); return { utf8Valid: !(text.match(/\uFFFD/g) ?? []).length, characterCount: Array.from(text).length, lineCount: text.split(/\r?\n/).length, previewHash: sha(text.slice(0, 1_000)) } }
function inspectAsset(buffer: Buffer, modality: MultimodalModality, contentType: string): Record<string, number | string | boolean> { if (modality === 'IMAGE') return inspectImage(buffer, contentType); if (modality === 'AUDIO' && ['audio/wav','audio/x-wav'].includes(contentType)) return inspectWav(buffer); if (modality === 'DOCUMENT') return inspectDocument(buffer, contentType); return { containerAccepted: true, semanticInferenceConfigured: false } }

export async function ingestMultimodalAsset(user: User, input: { name: string; contentType: string; bytes: Buffer; sensitivity: string; consentBasis: string; annotation?: string }): Promise<MultimodalAssetView> {
  const { schoolId } = requireOperator(user); const type = ALLOWED_TYPES[input.contentType.toLowerCase()]
  if (!type) throw new FederationError('INVALID_REQUEST', '仅支持 PNG/JPEG/GIF/WebP、WAV/MP3/OGG、MP4/WebM、TXT/Markdown/CSV/JSON/PDF')
  if (!input.bytes.length || input.bytes.length > MAX_ASSET_BYTES) throw new FederationError('INVALID_REQUEST', `文件大小必须为 1-${Math.floor(MAX_ASSET_BYTES / 1024 / 1024)}MB`)
  const consentBasis = input.consentBasis.trim(); if (consentBasis.length < 4 || consentBasis.length > 80) throw new FederationError('INVALID_REQUEST', '必须填写有效的数据授权或采集依据')
  if (!['PUBLIC','INTERNAL','RESTRICTED','CONFIDENTIAL'].includes(input.sensitivity)) throw new FederationError('INVALID_REQUEST', '数据敏感级别无效')
  const originalName = path.basename(input.name).replace(/[\u0000-\u001f]/g, '').slice(0, 260) || `asset${type.extension}`; const digest = sha(input.bytes)
  const existing = await getPostgresPool().query<{ id: string }>('SELECT id FROM ai_multimodal_assets WHERE school_id=$1::uuid AND sha256=$2', [schoolId, digest]); if (existing.rows[0]) return getMultimodalAsset(user, existing.rows[0].id)
  const objectKey = `${safeSegment(schoolId)}/${digest}${type.extension}`, finalPath = safePath('multimodal', objectKey), temporaryPath = safePath('multimodal', safeSegment(schoolId), `.upload-${randomUUID()}.tmp`)
  await mkdir(path.dirname(finalPath), { recursive: true }); await writeFile(temporaryPath, input.bytes, { flag: 'wx', mode: 0o600 })
  const metadata = inspectAsset(input.bytes, type.modality, input.contentType.toLowerCase()); const client = await getPostgresPool().connect(); let committed = false
  try {
    await client.query('BEGIN')
    const asset = await client.query<{ id: string }>(`INSERT INTO ai_multimodal_assets(school_id,object_key,original_name,modality,content_type,byte_size,sha256,sensitivity,consent_basis,status,technical_metadata,created_by) VALUES($1::uuid,$2,$3,$4,$5,$6,$7,$8,$9,'INSPECTED',$10::jsonb,$11) RETURNING id`, [schoolId, objectKey, originalName, type.modality, input.contentType.toLowerCase(), input.bytes.length, digest, input.sensitivity, consentBasis, JSON.stringify(metadata), user.id])
    const technicalSummary = type.modality === 'IMAGE' ? `已核验图像文件头与尺寸：${number(metadata.width)} × ${number(metadata.height)} 像素；尚未配置视觉语义模型，因此不生成物体识别结论。` : type.modality === 'AUDIO' ? `已核验音频容器与基础参数${metadata.durationSeconds ? `，时长约 ${metadata.durationSeconds} 秒` : ''}；未执行未经授权的声纹识别。` : type.modality === 'DOCUMENT' ? '已完成文档容器、编码与规模检查；原文保存在私有对象存储，不写入审计数据库。' : '已完成视频容器、类型与完整性登记；未配置视频语义模型，不生成虚构识别结论。'
    const evidence = { assetId: asset.rows[0].id, sha256: digest, metadata, extractionMode: 'DETERMINISTIC_TECHNICAL_INSPECTION' }
    await client.query(`INSERT INTO ai_multimodal_observations(school_id,asset_id,observation_type,label,summary,details,confidence,extraction_mode,evidence_hash) VALUES($1::uuid,$2::uuid,'TECHNICAL_INSPECTION',$3,$4,$5::jsonb,$6,'DETERMINISTIC_TECHNICAL_INSPECTION',$7)`, [schoolId, asset.rows[0].id, `${type.modality === 'IMAGE' ? '图像' : type.modality === 'AUDIO' ? '音频' : type.modality === 'DOCUMENT' ? '文档' : '视频'}技术校验`, technicalSummary, JSON.stringify(metadata), metadata.headerVerified === false ? 0.72 : 0.99, sha(JSON.stringify(evidence))])
    const annotation = input.annotation?.trim(); if (annotation) { if (annotation.length > 500) throw new FederationError('INVALID_REQUEST', '人工现场说明不能超过 500 个字符'); await client.query(`INSERT INTO ai_multimodal_observations(school_id,asset_id,observation_type,label,summary,details,confidence,extraction_mode,evidence_hash) VALUES($1::uuid,$2::uuid,'HUMAN_CONTEXT','现场人工说明',$3,'{"rawAssetNotEmbedded":true}'::jsonb,0.8,'HUMAN_CONTEXT',$4)`, [schoolId, asset.rows[0].id, annotation, sha(JSON.stringify({ assetId: asset.rows[0].id, annotationHash: sha(annotation), author: user.id }))]) }
    await client.query('COMMIT'); committed = true; await rename(temporaryPath, finalPath); return getMultimodalAsset(user, asset.rows[0].id)
  } catch (error) { if (!committed) await client.query('ROLLBACK'); try { await unlink(temporaryPath) } catch {} if (committed) await getPostgresPool().query("UPDATE ai_multimodal_assets SET status='REJECTED',updated_at=now() WHERE school_id=$1::uuid AND sha256=$2", [schoolId, digest]); throw error } finally { client.release() }
}

function mapObservation(row: Record<string, unknown>): MultimodalObservationView { return { id: String(row.id), type: String(row.observation_type), label: String(row.label), summary: String(row.summary), confidence: number(row.confidence), extractionMode: String(row.extraction_mode), evidenceHash: String(row.evidence_hash), status: String(row.status) as MultimodalObservationView['status'], reviewedAt: row.reviewed_at ? iso(row.reviewed_at) : undefined } }
function mapAsset(row: Record<string, unknown>, observations: MultimodalObservationView[]): MultimodalAssetView { return { id: String(row.id), originalName: String(row.original_name), modality: String(row.modality) as MultimodalModality, contentType: String(row.content_type), byteSize: number(row.byte_size), sha256: String(row.sha256), sensitivity: String(row.sensitivity), consentBasis: String(row.consent_basis), status: String(row.status) as MultimodalAssetView['status'], technicalMetadata: object(row.technical_metadata) as Record<string, number | string | boolean>, createdByName: String(row.created_by_name ?? 'AI 运维管理员'), createdAt: iso(row.created_at), observations } }
export async function getMultimodalAsset(user: User, assetId: string): Promise<MultimodalAssetView> { const { schoolId } = requireOperator(user); const [asset, observations] = await Promise.all([getPostgresPool().query(`SELECT a.*,u.name created_by_name FROM ai_multimodal_assets a LEFT JOIN users u ON u.id=a.created_by WHERE a.id=$1::uuid AND a.school_id=$2::uuid`, [assetId, schoolId]), getPostgresPool().query(`SELECT * FROM ai_multimodal_observations WHERE asset_id=$1::uuid AND school_id=$2::uuid ORDER BY created_at`, [assetId, schoolId])]); if (!asset.rows[0]) throw new FederationError('NOT_FOUND', '多模态资产不存在'); return mapAsset(asset.rows[0], observations.rows.map(mapObservation)) }
export async function reviewMultimodalObservation(user: User, observationId: string, decision: 'approve' | 'reject'): Promise<MultimodalAssetView> { const { schoolId } = requireOperator(user); const result = await getPostgresPool().query<{ asset_id: string }>(`UPDATE ai_multimodal_observations SET status=$3,reviewed_by=$2,reviewed_at=now() WHERE id=$1::uuid AND school_id=$4::uuid AND status='CANDIDATE' RETURNING asset_id`, [observationId, user.id, decision === 'approve' ? 'VERIFIED' : 'REJECTED', schoolId]); if (!result.rows[0]) throw new FederationError('NOT_FOUND', '待复核观察不存在或已经处理'); const status = await getPostgresPool().query<{ verified: number; pending: number }>(`SELECT count(*) FILTER(WHERE status='VERIFIED')::int verified,count(*) FILTER(WHERE status='CANDIDATE')::int pending FROM ai_multimodal_observations WHERE asset_id=$1::uuid`, [result.rows[0].asset_id]); const assetStatus = number(status.rows[0]?.verified) > 0 ? 'VERIFIED' : number(status.rows[0]?.pending) > 0 ? 'INSPECTED' : 'REJECTED'; await getPostgresPool().query('UPDATE ai_multimodal_assets SET status=$2,updated_at=now() WHERE id=$1::uuid', [result.rows[0].asset_id, assetStatus]); return getMultimodalAsset(user, result.rows[0].asset_id) }
export async function getMultimodalOverview(user: User): Promise<MultimodalOverview> {
  const { schoolId } = requireOperator(user); const [assets, observations, metrics] = await Promise.all([getPostgresPool().query(`SELECT a.*,u.name created_by_name FROM ai_multimodal_assets a LEFT JOIN users u ON u.id=a.created_by WHERE a.school_id=$1::uuid ORDER BY a.created_at DESC LIMIT 80`, [schoolId]), getPostgresPool().query(`SELECT * FROM ai_multimodal_observations WHERE school_id=$1::uuid ORDER BY created_at`, [schoolId]), getPostgresPool().query(`SELECT count(*)::int assets,count(*) FILTER(WHERE modality='IMAGE')::int images,count(*) FILTER(WHERE modality='AUDIO')::int audio,count(*) FILTER(WHERE modality='DOCUMENT')::int documents,count(*) FILTER(WHERE modality='VIDEO')::int videos,count(*) FILTER(WHERE status='VERIFIED')::int verified,COALESCE(sum(byte_size),0)::bigint total_bytes,(SELECT count(*)::int FROM ai_multimodal_observations WHERE school_id=$1::uuid AND status='CANDIDATE') pending FROM ai_multimodal_assets WHERE school_id=$1::uuid`, [schoolId])])
  const grouped = new Map<string, MultimodalObservationView[]>(); for (const row of observations.rows) grouped.set(String(row.asset_id), [...(grouped.get(String(row.asset_id)) ?? []), mapObservation(row)])
  const metric = metrics.rows[0]; return { persistent: true, storage: { backend: 'local_private_object_store', encryptedTransportRequired: true, rawBytesInDatabase: false, maximumBytes: MAX_ASSET_BYTES }, metrics: { assets: number(metric.assets), images: number(metric.images), audio: number(metric.audio), documents: number(metric.documents), videos: number(metric.videos), pendingReview: number(metric.pending), verified: number(metric.verified), totalBytes: number(metric.total_bytes) }, assets: assets.rows.map((row) => mapAsset(row, grouped.get(String(row.id)) ?? [])), guardrails: ['原始文件只进入租户私有对象存储，数据库仅保存对象键、哈希与技术元数据', '未配置视觉或语音语义模型时不生成虚构识别结论', '人工现场说明与机器技术校验分开标识', '观察结果必须由 AI 运维管理员复核后才能成为可信证据', '联邦任务只使用经过最小聚合阈值保护的统计量'] }
}

async function ensureNodeKey(schoolId: string, slug: string): Promise<{ publicKey: string; fingerprint: string; privateKeyPath: string }> {
  const folder = safePath('federation-keys', safeSegment(schoolId)); await mkdir(folder, { recursive: true })
  const privateKeyPath = safePath('federation-keys', safeSegment(schoolId), `${safeSegment(slug)}.private.pem`), publicKeyPath = safePath('federation-keys', safeSegment(schoolId), `${safeSegment(slug)}.public.pem`)
  try { const [privateKey, publicKey] = await Promise.all([readFile(privateKeyPath, 'utf8'), readFile(publicKeyPath, 'utf8')]); if (privateKey && publicKey) return { publicKey, fingerprint: sha(publicKey), privateKeyPath } } catch {}
  const pair = generateKeyPairSync('ed25519'), privateKey = pair.privateKey.export({ type: 'pkcs8', format: 'pem' }).toString(), publicKey = pair.publicKey.export({ type: 'spki', format: 'pem' }).toString()
  await writeFile(privateKeyPath, privateKey, { mode: 0o600 }); await writeFile(publicKeyPath, publicKey, { mode: 0o644 }); return { publicKey, fingerprint: sha(publicKey), privateKeyPath }
}
export async function ensureFederationNode(user: User, input: { slug: string; name: string; nodeKind: 'LOCAL' | 'SANDBOX'; capabilities: string[]; privacyPolicy?: { minimumGroupSize?: number; maxEpsilon30Days?: number } }): Promise<string> {
  const { schoolId } = requireOperator(user), slug = safeSegment(input.slug.toLowerCase()); if (slug.length < 3 || input.name.trim().length < 3) throw new FederationError('INVALID_REQUEST', '联邦节点标识或名称无效')
  const keys = await ensureNodeKey(schoolId, slug); const policy = { minimumGroupSize: Math.max(3, Math.round(input.privacyPolicy?.minimumGroupSize ?? DEFAULT_MINIMUM_GROUP)), maxEpsilon30Days: Math.max(0.1, Math.min(10, input.privacyPolicy?.maxEpsilon30Days ?? 6)) }
  const result = await getPostgresPool().query<{ id: string }>(`INSERT INTO ai_federation_nodes(school_id,slug,name,node_kind,transport,public_key,public_key_fingerprint,capabilities,privacy_policy,status,last_heartbeat_at,created_by) VALUES($1::uuid,$2,$3,$4,$5,$6,$7,$8::jsonb,$9::jsonb,'ACTIVE',now(),$10) ON CONFLICT(school_id,slug) DO UPDATE SET name=EXCLUDED.name,node_kind=EXCLUDED.node_kind,transport=EXCLUDED.transport,public_key=EXCLUDED.public_key,public_key_fingerprint=EXCLUDED.public_key_fingerprint,capabilities=EXCLUDED.capabilities,privacy_policy=EXCLUDED.privacy_policy,status='ACTIVE',last_heartbeat_at=now(),updated_at=now() RETURNING id`, [schoolId, slug, input.name.trim(), input.nodeKind, input.nodeKind === 'LOCAL' ? 'LOCAL_ADAPTER' : 'SANDBOX_ADAPTER', keys.publicKey, keys.fingerprint, JSON.stringify(input.capabilities), JSON.stringify(policy), user.id])
  return result.rows[0].id
}
interface AggregateRecord { modality: string; metric: string; value: number }
async function recordsForNode(schoolId: string, node: Record<string, unknown>, jobType: string, modalities: string[]): Promise<AggregateRecord[]> {
  if (node.node_kind === 'REMOTE') throw new FederationError('CONFLICT', '远程生产节点尚未完成互信配置')
  if (node.node_kind === 'SANDBOX') { const result = await getPostgresPool().query(`SELECT modality,metric,value::double precision value FROM ai_federation_sandbox_records WHERE school_id=$1::uuid AND node_id=$2::uuid AND quality='valid' AND (cardinality($3::text[])=0 OR modality=ANY($3::text[]))`, [schoolId, node.id, modalities]); return result.rows.map((row) => ({ modality: String(row.modality), metric: String(row.metric), value: number(row.value) })) }
  if (jobType === 'MULTIMODAL_METRICS') { const result = await getPostgresPool().query(`SELECT modality,'asset_size_kb' metric,(byte_size::double precision/1024) value FROM ai_multimodal_assets WHERE school_id=$1::uuid AND status IN ('INSPECTED','VERIFIED') AND (cardinality($2::text[])=0 OR modality=ANY($2::text[]))`, [schoolId, modalities]); return result.rows.map((row) => ({ modality: String(row.modality), metric: String(row.metric), value: number(row.value) })) }
  if (jobType === 'RETRIEVAL_TELEMETRY') { const result = await getPostgresPool().query(`SELECT 'DOCUMENT' modality,'retrieval_latency_ms' metric,latency_ms::double precision value FROM ai_knowledge_retrievals WHERE school_id=$1::uuid AND created_at>=now()-interval '30 days' AND latency_ms IS NOT NULL LIMIT 500`, [schoolId]); return result.rows.map((row) => ({ modality: String(row.modality), metric: String(row.metric), value: number(row.value) })) }
  const result = await getPostgresPool().query(`SELECT 'BUSINESS_METRIC' modality,metric,value FROM (SELECT 'repair_open' metric,count(*)::double precision value FROM repair_orders WHERE school_id=$1::uuid AND NOT is_deleted AND status<>'COMPLETED' UNION ALL SELECT 'safety_open',count(*)::double precision FROM dorm_safety_events WHERE school_id=$1::uuid AND status IN ('PENDING_CONFIRMATION','RECTIFICATION_REQUIRED','ESCALATED') UNION ALL SELECT 'visitor_pending',count(*)::double precision FROM visitors WHERE school_id=$1::uuid AND status='PENDING') metrics`, [schoolId]); return result.rows.map((row) => ({ modality: String(row.modality), metric: String(row.metric), value: number(row.value) }))
}
function deterministicUniform(seed: string): number { return createHash('sha256').update(seed).digest().readUInt32BE(0) / 0xffffffff }
function laplace(seed: string, scale: number): number { const uniform = deterministicUniform(seed) - 0.5; return -scale * Math.sign(uniform || 1) * Math.log(1 - 2 * Math.abs(uniform)) }

async function executeNodeContribution(input: { schoolId: string; user: User; jobId: string; node: Record<string, unknown>; jobType: string; modalities: string[]; minimumGroupSize: number; epsilonPerNode: number; purpose: string }): Promise<FederationContributionView> {
  const { schoolId, node } = input; const pool = getPostgresPool(), started = Date.now(); const capabilities = Array.isArray(node.capabilities) ? node.capabilities.map(String) : []
  let status: FederationContributionView['status'] = 'FAILED', errorCode: string | undefined, signature: string | undefined, signatureVerified = false, epsilonSpent = 0, records: AggregateRecord[] = [], payload: Record<string, unknown> = {}
  try {
    if (!capabilities.includes(input.jobType)) throw new FederationError('CONFLICT', 'NODE_CAPABILITY_MISMATCH')
    records = await recordsForNode(schoolId, node, input.jobType, input.modalities); const policy = object(node.privacy_policy); const nodeMinimum = Math.max(input.minimumGroupSize, number(policy.minimumGroupSize) || input.minimumGroupSize)
    if (records.length < nodeMinimum) { status = 'BELOW_THRESHOLD'; errorCode = 'MINIMUM_GROUP_NOT_MET' }
    else {
      const spent = await pool.query<{ total: number }>(`SELECT COALESCE(sum(epsilon_spent),0)::double precision total FROM ai_federation_privacy_ledger WHERE school_id=$1::uuid AND node_id=$2::uuid AND created_at>=now()-interval '30 days'`, [schoolId, node.id])
      if (number(spent.rows[0]?.total) + input.epsilonPerNode > number(policy.maxEpsilon30Days ?? 6)) { status = 'REJECTED'; errorCode = 'PRIVACY_BUDGET_EXHAUSTED' }
      else {
        epsilonSpent = Number(input.epsilonPerNode.toFixed(4)); const metricGroups = new Map<string, number[]>(), modalityCounts = new Map<string, number>()
        for (const record of records) { metricGroups.set(record.metric, [...(metricGroups.get(record.metric) ?? []), record.value]); modalityCounts.set(record.modality, (modalityCounts.get(record.modality) ?? 0) + 1) }
        const metricPayload = [...metricGroups.entries()].map(([metric, values]) => { const average = values.reduce((sum, value) => sum + value, 0) / values.length, range = Math.max(...values) - Math.min(...values), noisyAverage = average + laplace(`${input.jobId}:${node.id}:${metric}`, Math.max(0.001, range / values.length / Math.max(0.01, epsilonSpent))); return { metric, average: Number(noisyAverage.toFixed(4)), minimum: Number(Math.min(...values).toFixed(4)), maximum: Number(Math.max(...values).toFixed(4)), samples: values.length } })
        const protectedRecordCount = Math.max(nodeMinimum, Math.round(records.length + laplace(`${input.jobId}:${node.id}:count`, 1 / Math.max(0.01, epsilonSpent))))
        payload = { schemaVersion: 'federation.aggregate.v1', jobId: input.jobId, nodeId: node.id, protectedRecordCount, modalityCounts: Object.fromEntries([...modalityCounts.entries()].map(([key, value]) => [key, Math.max(0, Math.round(value + laplace(`${input.jobId}:${node.id}:${key}`, 1 / Math.max(0.01, epsilonSpent))))])), metrics: metricPayload, minimumGroupSize: nodeMinimum, differentialPrivacy: { mechanism: 'deterministic-seeded-laplace', epsilon: epsilonSpent }, rawRecordsTransferred: false }
        const payloadHash = sha(JSON.stringify(payload)), key = await ensureNodeKey(schoolId, String(node.slug)), privateKey = await readFile(key.privateKeyPath, 'utf8'); signature = cryptoSign(null, Buffer.from(payloadHash, 'utf8'), privateKey).toString('base64'); signatureVerified = cryptoVerify(null, Buffer.from(payloadHash, 'utf8'), String(node.public_key), Buffer.from(signature, 'base64'))
        if (!signatureVerified) throw new FederationError('CONFLICT', 'SIGNATURE_VERIFICATION_FAILED'); status = 'ACCEPTED'; await pool.query(`INSERT INTO ai_federation_privacy_ledger(school_id,node_id,job_id,purpose,epsilon_spent,approved_by) VALUES($1::uuid,$2::uuid,$3::uuid,$4,$5,$6)`, [schoolId, node.id, input.jobId, input.purpose, epsilonSpent, input.user.id])
      }
    }
  } catch (error) { errorCode = error instanceof FederationError ? error.message : 'NODE_EXECUTION_FAILED'; status = 'FAILED' }
  const payloadHash = sha(JSON.stringify(payload)), inserted = await pool.query<{ id: string }>(`INSERT INTO ai_federation_contributions(school_id,job_id,node_id,status,record_count,aggregate_payload,payload_hash,signature,signature_verified,epsilon_spent,latency_ms,error_code) VALUES($1::uuid,$2::uuid,$3::uuid,$4,$5,$6::jsonb,$7,$8,$9,$10,$11,$12) RETURNING id`, [schoolId, input.jobId, node.id, status, records.length, JSON.stringify(payload), payloadHash, signature ?? null, signatureVerified, epsilonSpent, Date.now() - started, errorCode ?? null])
  return { id: inserted.rows[0].id, nodeId: String(node.id), nodeName: String(node.name), nodeKind: String(node.node_kind) as FederationContributionView['nodeKind'], status, recordCount: records.length, protectedRecordCount: number(payload.protectedRecordCount) || undefined, signatureVerified, epsilonSpent, latencyMs: Date.now() - started, errorCode, metrics: Array.isArray(payload.metrics) ? payload.metrics as FederationContributionView['metrics'] : [] }
}

export async function runFederationJob(user: User, input: { name: string; jobType: 'MULTIMODAL_METRICS' | 'CAMPUS_RISK_AGGREGATION' | 'RETRIEVAL_TELEMETRY'; requestedModalities: string[]; minimumGroupSize: number; epsilonBudget: number }): Promise<FederationJobView> {
  const { schoolId } = requireOperator(user), name = input.name.trim(); if (name.length < 4 || name.length > 220) throw new FederationError('INVALID_REQUEST', '联邦任务名称需为 4-220 个字符')
  const minimumGroupSize = Math.round(input.minimumGroupSize); if (minimumGroupSize < 3 || minimumGroupSize > 1_000) throw new FederationError('INVALID_REQUEST', '最小聚合阈值需为 3-1000'); if (!(input.epsilonBudget > 0 && input.epsilonBudget <= 10)) throw new FederationError('INVALID_REQUEST', '隐私预算必须大于 0 且不超过 10')
  const modalities = [...new Set(input.requestedModalities.filter((item) => ['IMAGE','AUDIO','DOCUMENT','VIDEO','BUSINESS_METRIC'].includes(item)))], pool = getPostgresPool()
  const job = await pool.query<{ id: string; created_at: unknown }>(`INSERT INTO ai_federation_jobs(school_id,name,job_type,query_hash,requested_modalities,minimum_group_size,epsilon_budget,status,initiated_by,started_at) VALUES($1::uuid,$2,$3,$4,$5::text[],$6,$7,'RUNNING',$8,now()) RETURNING id,created_at`, [schoolId, name, input.jobType, sha(JSON.stringify({ jobType: input.jobType, modalities, minimumGroupSize })), modalities, minimumGroupSize, input.epsilonBudget, user.id])
  const nodes = await pool.query(`SELECT * FROM ai_federation_nodes WHERE school_id=$1::uuid AND status='ACTIVE' ORDER BY node_kind,slug`, [schoolId]), epsilonPerNode = nodes.rows.length > 0 ? input.epsilonBudget / nodes.rows.length : 0, contributions: FederationContributionView[] = []
  for (const node of nodes.rows) contributions.push(await executeNodeContribution({ schoolId, user, jobId: job.rows[0].id, node, jobType: input.jobType, modalities, minimumGroupSize, epsilonPerNode, purpose: `${input.jobType}：${name}` }))
  const accepted = contributions.filter((item) => item.status === 'ACCEPTED' && item.signatureVerified), metricAccumulator = new Map<string, Array<{ value: number; weight: number }>>(), modalityCounts: Record<string, number> = {}; let protectedRecords = 0
  for (const contribution of accepted) {
    protectedRecords += contribution.protectedRecordCount ?? 0; for (const metric of contribution.metrics) metricAccumulator.set(metric.metric, [...(metricAccumulator.get(metric.metric) ?? []), { value: metric.average, weight: Math.max(1, metric.samples) }])
    const sourcePayload = object((await pool.query<{ aggregate_payload: unknown }>('SELECT aggregate_payload FROM ai_federation_contributions WHERE id=$1::uuid', [contribution.id])).rows[0]?.aggregate_payload); for (const [key, value] of Object.entries(object(sourcePayload.modalityCounts))) modalityCounts[key] = (modalityCounts[key] ?? 0) + number(value)
  }
  const aggregate = { participatingNodes: accepted.length, protectedRecords, metrics: [...metricAccumulator.entries()].map(([metric, values]) => ({ metric, average: Number((values.reduce((sum, item) => sum + item.value * item.weight, 0) / values.reduce((sum, item) => sum + item.weight, 0)).toFixed(4)), nodes: values.length })), modalityCounts }
  const status = accepted.length === nodes.rows.length && accepted.length > 0 ? 'COMPLETED' : accepted.length > 0 ? 'PARTIAL' : 'BLOCKED', resultHash = sha(JSON.stringify(aggregate)); await pool.query('UPDATE ai_federation_jobs SET status=$2,aggregate_result=$3::jsonb,result_hash=$4,completed_at=now() WHERE id=$1::uuid', [job.rows[0].id, status, JSON.stringify(aggregate), resultHash])
  return { id: job.rows[0].id, name, jobType: input.jobType, requestedModalities: modalities, minimumGroupSize, epsilonBudget: input.epsilonBudget, status, aggregate, resultHash, contributions, createdAt: iso(job.rows[0].created_at), completedAt: new Date().toISOString() }
}
function mapContribution(row: Record<string, unknown>): FederationContributionView { const payload = object(row.aggregate_payload); return { id: String(row.id), nodeId: String(row.node_id), nodeName: String(row.node_name), nodeKind: String(row.node_kind) as FederationContributionView['nodeKind'], status: String(row.status) as FederationContributionView['status'], recordCount: number(row.record_count), protectedRecordCount: number(payload.protectedRecordCount) || undefined, signatureVerified: Boolean(row.signature_verified), epsilonSpent: number(row.epsilon_spent), latencyMs: number(row.latency_ms), errorCode: typeof row.error_code === 'string' ? row.error_code : undefined, metrics: Array.isArray(payload.metrics) ? payload.metrics as FederationContributionView['metrics'] : [] } }
export async function getFederationOverview(user: User): Promise<FederationOverview> {
  const { schoolId } = requireOperator(user), pool = getPostgresPool()
  const [nodesResult, jobsResult, contributionsResult, metricsResult] = await Promise.all([
    pool.query(`SELECT n.*,COALESCE((SELECT sum(epsilon_spent)::double precision FROM ai_federation_privacy_ledger l WHERE l.node_id=n.id AND l.created_at>=now()-interval '30 days'),0) epsilon_spent FROM ai_federation_nodes n WHERE n.school_id=$1::uuid ORDER BY n.node_kind,n.name`, [schoolId]),
    pool.query(`SELECT * FROM ai_federation_jobs WHERE school_id=$1::uuid ORDER BY created_at DESC LIMIT 30`, [schoolId]),
    pool.query(`SELECT c.*,n.name node_name,n.node_kind FROM ai_federation_contributions c JOIN ai_federation_nodes n ON n.id=c.node_id WHERE c.school_id=$1::uuid ORDER BY c.created_at`, [schoolId]),
    pool.query(`SELECT (SELECT count(*)::int FROM ai_federation_nodes WHERE school_id=$1::uuid AND status='ACTIVE') active_nodes,(SELECT count(*)::int FROM ai_federation_nodes WHERE school_id=$1::uuid AND node_kind='SANDBOX') sandbox_nodes,(SELECT count(*)::int FROM ai_federation_nodes WHERE school_id=$1::uuid AND node_kind='REMOTE' AND status='ACTIVE') remote_nodes,(SELECT count(*)::int FROM ai_federation_jobs WHERE school_id=$1::uuid AND status IN ('COMPLETED','PARTIAL')) completed_jobs,(SELECT count(*)::int FROM ai_federation_contributions WHERE school_id=$1::uuid AND status='ACCEPTED' AND signature_verified) verified_contributions,(SELECT COALESCE(sum(epsilon_spent),0)::double precision FROM ai_federation_privacy_ledger WHERE school_id=$1::uuid AND created_at>=now()-interval '30 days') epsilon_spent`, [schoolId]),
  ])
  const contributionsByJob = new Map<string, FederationContributionView[]>(); for (const row of contributionsResult.rows) contributionsByJob.set(String(row.job_id), [...(contributionsByJob.get(String(row.job_id)) ?? []), mapContribution(row)])
  const jobs: FederationJobView[] = jobsResult.rows.map((row) => { const aggregate = object(row.aggregate_result); return { id: String(row.id), name: String(row.name), jobType: String(row.job_type), requestedModalities: Array.isArray(row.requested_modalities) ? row.requested_modalities.map(String) : [], minimumGroupSize: number(row.minimum_group_size), epsilonBudget: number(row.epsilon_budget), status: String(row.status), aggregate: { participatingNodes: number(aggregate.participatingNodes), protectedRecords: number(aggregate.protectedRecords), metrics: Array.isArray(aggregate.metrics) ? aggregate.metrics as FederationJobView['aggregate']['metrics'] : [], modalityCounts: Object.fromEntries(Object.entries(object(aggregate.modalityCounts)).map(([key, value]) => [key, number(value)])) }, resultHash: typeof row.result_hash === 'string' ? row.result_hash : undefined, contributions: contributionsByJob.get(String(row.id)) ?? [], createdAt: iso(row.created_at), completedAt: row.completed_at ? iso(row.completed_at) : undefined } })
  const nodes: FederationNodeView[] = nodesResult.rows.map((row) => { const policy = object(row.privacy_policy); return { id: String(row.id), slug: String(row.slug), name: String(row.name), nodeKind: String(row.node_kind) as FederationNodeView['nodeKind'], transport: String(row.transport), status: String(row.status), capabilities: Array.isArray(row.capabilities) ? row.capabilities.map(String) : [], fingerprint: String(row.public_key_fingerprint), lastHeartbeatAt: row.last_heartbeat_at ? iso(row.last_heartbeat_at) : undefined, privacy: { minimumGroupSize: number(policy.minimumGroupSize), maxEpsilon30Days: number(policy.maxEpsilon30Days), epsilonSpent30Days: number(row.epsilon_spent) } } })
  const metric = metricsResult.rows[0]; return { persistent: true, metrics: { activeNodes: number(metric.active_nodes), sandboxNodes: number(metric.sandbox_nodes), remoteProductionNodes: number(metric.remote_nodes), completedJobs: number(metric.completed_jobs), verifiedContributions: number(metric.verified_contributions), epsilonSpent30Days: number(metric.epsilon_spent) }, nodes, jobs, protocol: { signing: 'Ed25519', rawRecordsTransferred: false, minimumAggregation: DEFAULT_MINIMUM_GROUP, privacyLedger: true, note: '当前联邦由本地真实节点与明确标注的隔离沙箱节点组成；尚无远程生产学校节点，不伪造跨校上线状态。' } }
}
