'use client'

import Link from 'next/link'
import { useCallback, useEffect, useMemo, useState } from 'react'
import { Activity, ArrowDown, ArrowRight, Building2, CheckCircle2, Cpu, Gauge, GitCompareArrows, Loader2, Radio, RefreshCw, Send, ShieldCheck, Sparkles, TriangleAlert, Users, Waves, Wrench, Zap } from 'lucide-react'
import { MainLayout } from '@/components/layout'
import { BaizeAvatar } from '@/components/ai/baize-avatar'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Switch } from '@/components/ui/switch'
import { useAuthStore } from '@/stores'
import { UserRole } from '@/types'
import type { TwinInterventions, TwinMetrics, TwinOverview, TwinSimulationView } from '@/lib/ai/platform/twin-types'

const DEFAULT_INTERVENTIONS: TwinInterventions = { repairCapacityDelta: 4, energyReductionPct: 12, notificationEscalation: true, visitorDeskDelta: 2, eventAttendees: 800 }
const SOURCE_LABELS: Record<string,string> = { repairs: '报修工单', classrooms: '教学空间', energyReadings: '能耗读数', visitors: '访客申请', safetyEvents: '安全事件', deliveries: '通知回执', materials: '物资告警', buildings: '校园建筑' }
function pct(value: number): string { return `${Math.round(value * 100)}%` }
function date(value?: string): string { return value ? new Date(value).toLocaleString('zh-CN') : '—' }
function delta(value: number, suffix = ''): string { return `${value > 0 ? '+' : ''}${value}${suffix}` }

function RiskGauge({ value, label }: { value: number; label: string }) {
  const color = value >= 75 ? '#fb7185' : value >= 50 ? '#fbbf24' : '#34d399'
  return <div className="relative flex h-32 w-32 items-center justify-center rounded-full" style={{ background: `conic-gradient(${color} ${value * 3.6}deg,rgba(148,163,184,.16) 0)` }}><div className="flex h-[104px] w-[104px] flex-col items-center justify-center rounded-full bg-white"><p className="text-3xl font-bold text-slate-900">{value}</p><p className="text-[10px] text-slate-500">{label}</p></div></div>
}
function MetricPair({ label, baseline, projected, suffix = '', lowerBetter = true }: { label: string; baseline: number; projected: number; suffix?: string; lowerBetter?: boolean }) {
  const improvement = lowerBetter ? projected <= baseline : projected >= baseline
  const maximum = Math.max(1, baseline, projected)
  return (
    <div className="rounded-2xl border bg-white p-4">
      <div className="flex items-center justify-between">
        <p className="text-xs font-medium text-slate-600">{label}</p>
        <Badge className={improvement ? 'bg-emerald-100 text-emerald-700' : 'bg-amber-100 text-amber-700'}>{improvement ? '改善' : '需关注'}</Badge>
      </div>
      <div className="mt-3 space-y-2">
        <div><div className="mb-1 flex justify-between text-[11px] text-slate-500"><span>当前</span><b>{baseline}{suffix}</b></div><div className="h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-slate-400" style={{ width: `${baseline / maximum * 100}%` }} /></div></div>
        <div><div className="mb-1 flex justify-between text-[11px] text-cyan-700"><span>推演</span><b>{projected}{suffix}</b></div><div className="h-2 rounded-full bg-cyan-100"><div className="h-2 rounded-full bg-gradient-to-r from-cyan-500 to-blue-500" style={{ width: `${projected / maximum * 100}%` }} /></div></div>
      </div>
    </div>
  )
}
function CampusTopology({ overview }: { overview: TwinOverview }) {
  const nodes = overview.snapshot?.topology ?? []
  return <div className="relative overflow-hidden rounded-3xl border border-cyan-300/15 bg-[#071321] p-4 text-white"><div className="absolute inset-0 opacity-30 [background-image:linear-gradient(rgba(34,211,238,.12)_1px,transparent_1px),linear-gradient(90deg,rgba(34,211,238,.12)_1px,transparent_1px)] [background-size:28px_28px]" /><svg viewBox="0 0 100 70" className="relative h-[360px] w-full" role="img" aria-label="校园数字孪生拓扑"><defs><filter id="glow"><feGaussianBlur stdDeviation="1.2" result="blur"/><feMerge><feMergeNode in="blur"/><feMergeNode in="SourceGraphic"/></feMerge></filter><linearGradient id="thread"><stop stopColor="#22d3ee"/><stop offset="1" stopColor="#8b5cf6"/></linearGradient></defs>{nodes.map((node,index)=>{const angle=index/nodes.length*Math.PI*2-Math.PI/2,x=50+Math.cos(angle)*34,y=35+Math.sin(angle)*25;return <g key={`line-${node.id}`}><path d={`M50 35 Q${(50+x)/2 + Math.sin(angle)*7} ${(35+y)/2} ${x} ${y}`} fill="none" stroke="url(#thread)" strokeWidth=".45" strokeDasharray="2 1" opacity=".7"><animate attributeName="stroke-dashoffset" values="0;-12" dur="3s" repeatCount="indefinite"/></path></g>})}<g filter="url(#glow)"><circle cx="50" cy="35" r="9" fill="#0e7490" stroke="#67e8f9" strokeWidth=".6"/><circle cx="50" cy="35" r="12" fill="none" stroke="#22d3ee" strokeWidth=".3" opacity=".55"><animate attributeName="r" values="10;14;10" dur="3s" repeatCount="indefinite"/></circle><text x="50" y="34" textAnchor="middle" fontSize="3.4" fill="white" fontWeight="700">白泽主脑</text><text x="50" y="38.2" textAnchor="middle" fontSize="2.2" fill="#a5f3fc">实时态势核验</text></g>{nodes.map((node,index)=>{const angle=index/nodes.length*Math.PI*2-Math.PI/2,x=50+Math.cos(angle)*34,y=35+Math.sin(angle)*25,risk=node.safetyCount*2+node.repairCount;const color=risk>=5?'#fb7185':risk>=2?'#fbbf24':'#34d399';return <g key={node.id} filter="url(#glow)"><circle cx={x} cy={y} r="6.5" fill="#0f2238" stroke={color} strokeWidth=".55"/><circle cx={x} cy={y} r="8" fill="none" stroke={color} strokeWidth=".25" opacity=".5"><animate attributeName="opacity" values=".2;.7;.2" dur={`${2.4+index*.35}s`} repeatCount="indefinite"/></circle><text x={x} y={y-1} textAnchor="middle" fontSize="2.5" fill="white" fontWeight="600">{node.name.slice(0,9)}</text><text x={x} y={y+2.6} textAnchor="middle" fontSize="1.9" fill="#94a3b8">工单 {node.repairCount} · 安全 {node.safetyCount}</text></g>})}</svg><div className="relative -mt-2 flex flex-wrap justify-center gap-2 text-[10px]"><span className="rounded-full border border-emerald-300/20 bg-emerald-300/10 px-2 py-1 text-emerald-200">运行平稳</span><span className="rounded-full border border-amber-300/20 bg-amber-300/10 px-2 py-1 text-amber-200">需要关注</span><span className="rounded-full border border-rose-300/20 bg-rose-300/10 px-2 py-1 text-rose-200">风险聚集</span></div></div>
}

export default function TwinPage() {
  const user = useAuthStore((state)=>state.user)
  const [overview,setOverview]=useState<TwinOverview|null>(null),[interventions,setInterventions]=useState<TwinInterventions>(DEFAULT_INTERVENTIONS),[busy,setBusy]=useState<string|null>(null),[error,setError]=useState<string|null>(null),[notice,setNotice]=useState<string|null>(null)
  const load=useCallback(async()=>{try{const response=await fetch('/api/ai/twin',{cache:'no-store'}),json=await response.json();if(!response.ok||!json.success)throw new Error(json.error??'数字孪生加载失败');setOverview(json.data)}catch(e){setError(e instanceof Error?e.message:'数字孪生加载失败')}},[])
  useEffect(()=>{void load()},[load])
  async function action(body:Record<string,unknown>,key:string,message:string){setBusy(key);setError(null);setNotice(null);try{const response=await fetch('/api/ai/twin',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}),json=await response.json();if(!response.ok||!json.success)throw new Error(json.error??'操作未完成');setNotice(message);await load();return json.data}catch(e){setError(e instanceof Error?e.message:'操作未完成')}finally{setBusy(null)}}
  const simulation=overview?.latestSimulation,baseline=simulation?.baseline??overview?.snapshot?.metrics,projected=simulation?.projected??baseline,canDispatch=user?.role===UserRole.SUPER_ADMIN||user?.role===UserRole.LOGISTICS_MANAGER
  const sourceTotal=useMemo(()=>Object.values(overview?.snapshot?.sourceCounts??{}).reduce((sum,value)=>sum+value,0),[overview])
  if(!overview&&!error)return <MainLayout><div className="flex min-h-[70vh] items-center justify-center"><Loader2 className="h-8 w-8 animate-spin text-cyan-600" /></div></MainLayout>
  return <MainLayout><div data-testid="digital-twin-workbench" className="space-y-6 pb-10">
    <section className="relative overflow-hidden rounded-[28px] border border-cyan-300/20 bg-[radial-gradient(circle_at_82%_15%,rgba(34,211,238,.18),transparent_28%),linear-gradient(135deg,#06111f,#0a2032_58%,#171437)] px-6 py-7 text-white shadow-2xl md:px-9" style={{ background: 'radial-gradient(circle at 82% 15%, rgba(34,211,238,.18), transparent 28%), linear-gradient(135deg,#06111f,#0a2032 58%,#171437)' }}><div className="relative flex flex-wrap items-center justify-between gap-7"><div className="max-w-3xl"><div className="flex flex-wrap gap-2"><Badge className="border border-cyan-200/20 bg-cyan-200/10 text-cyan-100"><Building2 className="mr-1 h-3.5 w-3.5" />校园数字孪生驾驶舱</Badge><Badge className="border border-emerald-200/20 bg-emerald-200/10 text-emerald-100"><Radio className="mr-1 h-3 w-3" />真实业务快照</Badge></div><h1 className="mt-4 text-3xl font-semibold md:text-4xl">把校园运行态势变成可推演、可解释、可下发的决策空间</h1><p className="mt-3 max-w-2xl text-sm leading-7 text-slate-300">白泽读取工单、空间、能耗、访客、安全、通知、物资与 Agent 状态构建孪生快照。所有预测均标注假设，不写业务库；采纳建议仍进入正式审批链。</p><div className="mt-5 flex flex-wrap gap-2 text-xs text-slate-300"><span className="rounded-full border border-white/10 bg-white/5 px-3 py-1.5">模型 {overview?.model.version}</span><span className="rounded-full border border-white/10 bg-white/5 px-3 py-1.5">源记录 {sourceTotal}</span><span className="rounded-full border border-white/10 bg-white/5 px-3 py-1.5">质量 {pct(overview?.snapshot?.dataQualityScore??0)}</span><span className="rounded-full border border-white/10 bg-white/5 px-3 py-1.5">快照 {date(overview?.snapshot?.observedAt)}</span></div></div><BaizeAvatar mood={busy?'busy':'success'} size={190} showThreads threadCount={5}/></div></section>
    {error&&<div className="flex gap-2 rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700"><TriangleAlert className="h-4 w-4"/>{error}</div>}{notice&&<div className="flex gap-2 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-800"><CheckCircle2 className="h-4 w-4"/>{notice}</div>}
    {overview&&<div className="grid gap-5 xl:grid-cols-[minmax(0,1.25fr)_minmax(380px,.75fr)]"><CampusTopology overview={overview}/><Card><CardHeader><div className="flex items-center justify-between"><CardTitle className="flex items-center gap-2 text-base"><Cpu className="h-5 w-5 text-cyan-600"/>情景干预控制台</CardTitle><Button size="sm" variant="outline" disabled={Boolean(busy)} onClick={()=>void action({action:'capture'},'capture','已从真实业务库生成新的孪生快照。')}><RefreshCw className={`mr-1 h-4 w-4 ${busy==='capture'?'animate-spin':''}`}/>刷新快照</Button></div></CardHeader><CardContent className="space-y-4">{[
      {key:'repairCapacityDelta',label:'工程师增援',value:interventions.repairCapacityDelta,max:20,suffix:' 人',icon:Wrench},{key:'energyReductionPct',label:'能耗削峰目标',value:interventions.energyReductionPct,max:30,suffix:'%',icon:Zap},{key:'visitorDeskDelta',label:'访客核验席位',value:interventions.visitorDeskDelta,max:10,suffix:' 个',icon:Users},{key:'eventAttendees',label:'活动参与人数',value:interventions.eventAttendees,max:5000,step:100,suffix:' 人',icon:Activity},
    ].map(item=><div key={item.key} className="rounded-xl border bg-slate-50 p-3"><div className="flex items-center justify-between text-sm"><span className="flex items-center gap-2 font-medium"><item.icon className="h-4 w-4 text-cyan-600"/>{item.label}</span><b>{item.value}{item.suffix}</b></div><input aria-label={item.label} type="range" min="0" max={item.max} step={item.step??1} value={item.value} onChange={event=>setInterventions(current=>({...current,[item.key]:Number(event.target.value)}))} className="mt-3 w-full accent-cyan-600"/></div>)}<div className="flex items-center justify-between rounded-xl border bg-slate-50 p-3"><div><p className="text-sm font-medium">未确认通知升级</p><p className="mt-1 text-xs text-slate-500">由灵鹊触发人工跟进建议</p></div><Switch checked={interventions.notificationEscalation} onCheckedChange={value=>setInterventions(current=>({...current,notificationEscalation:value}))}/></div><Button className="w-full" disabled={Boolean(busy)} onClick={()=>void action({action:'simulate',name:`校园联合保障推演 · ${interventions.eventAttendees}人场景`,hypothesis:'在真实运行快照上评估资源增援、能耗削峰、通知升级与访客席位调整对校园风险的综合影响。',snapshotId:overview.snapshot?.id,interventions},'simulate','白泽已完成可复现推演，结果不会直接改写业务数据。')}>{busy==='simulate'?<Loader2 className="mr-2 h-4 w-4 animate-spin"/>:<Sparkles className="mr-2 h-4 w-4"/>}执行真实快照推演</Button></CardContent></Card></div>}
    {baseline&&projected&&<><Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><GitCompareArrows className="h-5 w-5 text-violet-600"/>当前态势与推演结果</CardTitle></CardHeader><CardContent><div className="grid items-center gap-5 lg:grid-cols-[150px_1fr_70px_1fr_150px]"><RiskGauge value={baseline.campusRiskScore} label="当前风险"/><div className="grid grid-cols-2 gap-3"><MetricPair label="超时工单" baseline={baseline.repairs.overdue} projected={projected.repairs.overdue}/><MetricPair label="平均闭环" baseline={baseline.repairs.averageResolutionHours} projected={projected.repairs.averageResolutionHours} suffix="h"/></div><div className="flex justify-center"><ArrowRight className="h-8 w-8 text-cyan-500"/></div><div className="grid grid-cols-2 gap-3"><MetricPair label="能耗负荷" baseline={baseline.energy.loadKw} projected={projected.energy.loadKw} suffix="kW"/><MetricPair label="通知确认率" baseline={Math.round(baseline.communications.acknowledgementRate*100)} projected={Math.round(projected.communications.acknowledgementRate*100)} suffix="%" lowerBetter={false}/></div><RiskGauge value={projected.campusRiskScore} label="推演风险"/></div>{simulation&&<div className="mt-5 flex flex-wrap gap-2">{Object.entries(simulation.deltas).map(([key,value])=><span key={key} className={`rounded-full border px-3 py-1 text-xs ${value<0?'border-emerald-200 bg-emerald-50 text-emerald-700':value>0?'border-amber-200 bg-amber-50 text-amber-700':'border-slate-200 text-slate-500'}`}>{key==='campusRiskScore'?'综合风险':key==='energyLoadKw'?'能耗负荷':key==='acknowledgementRate'?'确认率':key==='visitorQueue'?'访客队列':key==='overdueRepairs'?'超时工单':key==='openRepairs'?'开放工单':'闭环时长'} {delta(key==='acknowledgementRate'?Math.round(value*100):value,key==='acknowledgementRate'?'%':'')}</span>)}</div>}</CardContent></Card>
    {simulation&&<div className="grid gap-5 xl:grid-cols-[1fr_.8fr]"><Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><ShieldCheck className="h-5 w-5 text-emerald-600"/>白泽决策建议</CardTitle></CardHeader><CardContent className="space-y-3">{simulation.recommendations.map(rec=><div key={rec.id} className="rounded-2xl border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold text-slate-900">{rec.title}</p><p className="mt-2 text-sm leading-6 text-slate-600">{rec.summary}</p></div><Badge className={rec.status==='DISPATCHED'?'bg-emerald-100 text-emerald-700':'bg-cyan-100 text-cyan-700'}>{rec.status==='DISPATCHED'?'已进入审批链':'待采纳'}</Badge></div><div className="mt-3 flex gap-2">{rec.taskId?<Button asChild size="sm"><Link href={`/ai-agents/runtime?task=${rec.taskId}`}>查看 Agent 执行星图</Link></Button>:<Button size="sm" disabled={!canDispatch||Boolean(busy)} onClick={()=>void action({action:'dispatch',recommendationId:rec.id},`dispatch-${rec.id}`,'建议已转成正式 Agent 任务，并停在人工审批节点。')}><Send className="mr-1 h-4 w-4"/>{canDispatch?'下发至白泽 Agent 团队':'交由业务负责人下发'}</Button>}</div></div>)}</CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Gauge className="h-5 w-5 text-amber-600"/>模型可信边界</CardTitle></CardHeader><CardContent className="space-y-3"><div className="rounded-2xl bg-slate-50 p-4"><div className="flex items-center justify-between"><span className="text-sm text-slate-600">综合置信度</span><b className="text-xl">{pct(simulation.confidence)}</b></div><div className="mt-2 h-2 rounded-full bg-slate-200"><div className="h-2 rounded-full bg-gradient-to-r from-amber-400 to-emerald-500" style={{width:pct(simulation.confidence)}}/></div></div>{simulation.assumptions.map((item,index)=><div key={item} className="flex gap-2 rounded-xl border p-3 text-xs leading-5 text-slate-600"><span className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-slate-900 text-[10px] text-white">{index+1}</span>{item}</div>)}<p className="text-[10px] text-slate-400">证据指纹 {simulation.evidenceHash?.slice(0,18)}… · 引擎 {simulation.engineVersion}</p></CardContent></Card></div>}</>}
    {overview?.snapshot&&<Card className="border-cyan-200 bg-cyan-50/40"><CardContent className="grid gap-3 p-4 sm:grid-cols-4 lg:grid-cols-8">{Object.entries(overview.snapshot.sourceCounts).map(([key,value])=><div key={key} className="rounded-xl border border-cyan-100 bg-white p-3"><p className="text-[10px] text-slate-500">{SOURCE_LABELS[key]??key}</p><p className="mt-1 text-xl font-bold text-slate-900">{value}</p></div>)}</CardContent></Card>}
  </div></MainLayout>
}
