import './assert-isolated-test-environment.mjs'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import path from 'node:path'
import { getPostgresPool } from '@/storage/database/postgres'
import { AI_MULTIMODAL_FEDERATION_TABLES, AI_TWIN_TABLES } from '@/storage/database/schema/platform'
import { TWIN_SIMULATION_NEVER_WRITES_BUSINESS_DATA } from '@/lib/ai/platform/twin'
const TWIN=['ai_twin_models','ai_twin_snapshots','ai_twin_scenarios','ai_twin_simulation_runs','ai_twin_recommendations']
const FED=['ai_multimodal_assets','ai_multimodal_observations','ai_federation_nodes','ai_federation_sandbox_records','ai_federation_jobs','ai_federation_contributions','ai_federation_privacy_ledger']
async function main(){const migration=await readFile(path.resolve('drizzle/0013_digital_twin_multimodal_federation.sql'),'utf8'),schema=await readFile(path.resolve('src/storage/database/schema/platform.ts'),'utf8');let assertions=0;const expect=(v:unknown,m:string)=>{assert.ok(v,m);assertions++}
expect(AI_TWIN_TABLES.length===5,'twin registry incomplete');expect(AI_MULTIMODAL_FEDERATION_TABLES.length===7,'federation registry incomplete');for(const table of [...TWIN,...FED]){expect(migration.includes(`CREATE TABLE IF NOT EXISTS ${table}`),`migration missing ${table}`);expect(schema.includes(`pgTable('${table}'`),`schema missing ${table}`)}expect(migration.includes('data_quality_score numeric(8,5)'),'twin data quality evidence missing');expect(migration.includes('baseline_metrics jsonb NOT NULL')&&migration.includes('projected_metrics jsonb NOT NULL'),'twin baseline/projection persistence missing');expect(migration.includes('task_id uuid REFERENCES ai_task_runs(id)'),'twin recommendations do not link governed tasks');expect(migration.includes('sha256 varchar(64) NOT NULL'),'multimodal object integrity missing');expect(migration.includes('signature_verified boolean NOT NULL'),'federation signature verification missing');expect(migration.includes('minimum_group_size integer NOT NULL'),'minimum aggregation threshold missing');expect(migration.includes('epsilon_spent numeric(8,4) NOT NULL'),'privacy ledger missing');expect(migration.includes('REVOKE ALL ON TABLE %I FROM PUBLIC, anon, authenticated'),'direct access not revoked');expect(TWIN_SIMULATION_NEVER_WRITES_BUSINESS_DATA,'twin simulation business-write guard missing')
const pool=getPostgresPool(),tables=[...TWIN,...FED];const live=await pool.query<{table_name:string;row_security:boolean}>(`SELECT c.relname table_name,c.relrowsecurity row_security FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relname=ANY($1::text[])`,[tables]);expect(live.rows.length===12,'live twin/federation tables missing');expect(live.rows.every(row=>row.row_security),'twin/federation RLS missing');const applied=await pool.query("SELECT 1 FROM schema_migrations WHERE name='0013_digital_twin_multimodal_federation.sql'");expect(applied.rows.length===1,'migration not recorded');console.log(`PASS twin/multimodal/federation migration: tables=12 RLS=true simulationReadOnly=true signedAggregates=true assertions=${assertions}`)}
main().catch(error=>{console.error(error);process.exitCode=1})
