import './assert-isolated-test-environment.mjs'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import path from 'node:path'
import { getPostgresPool } from '@/storage/database/postgres'
import { AI_COLLABORATION_TABLES } from '@/storage/database/schema/platform'
const TABLES=['ai_collaboration_rooms','ai_collaboration_notes','ai_collaboration_deliverables']
async function main(){const migration=await readFile(path.resolve('drizzle/0011_multi_agent_collaboration.sql'),'utf8');const schema=await readFile(path.resolve('src/storage/database/schema/platform.ts'),'utf8');let assertions=0;const expect=(v:unknown,m:string)=>{assert.ok(v,m);assertions++};expect(AI_COLLABORATION_TABLES.length===3,'collaboration table registry incomplete');for(const table of TABLES){expect(migration.includes(`CREATE TABLE IF NOT EXISTS ${table}`),`migration missing ${table}`);expect(schema.includes(`pgTable('${table}'`),`schema missing ${table}`)}expect(migration.includes('task_id uuid NOT NULL REFERENCES ai_task_runs(id)'),'collaboration rooms are not linked to authoritative tasks');expect(migration.includes('content_hash varchar(64) NOT NULL'),'human notes lack integrity hashes');expect(migration.includes("status IN ('PENDING','IN_PROGRESS','READY_FOR_REVIEW','ACCEPTED','BLOCKED','FAILED')"),'deliverable review lifecycle missing');expect(migration.includes('evidence_refs jsonb NOT NULL'),'deliverable evidence references missing');expect(migration.includes('REVOKE ALL ON TABLE %I FROM PUBLIC, anon, authenticated'),'direct collaboration access not revoked');const pool=getPostgresPool();const live=await pool.query<{table_name:string;row_security:boolean}>(`SELECT c.relname table_name,c.relrowsecurity row_security FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relname=ANY($1::text[]) ORDER BY c.relname`,[TABLES]);expect(live.rows.length===3,'live collaboration tables missing');expect(live.rows.every(r=>r.row_security),'collaboration RLS missing');const applied=await pool.query("SELECT name FROM schema_migrations WHERE name='0011_multi_agent_collaboration.sql'");expect(applied.rows.length===1,'collaboration migration not recorded');console.log(`PASS multi-Agent collaboration migration: tables=3 RLS=true taskSource=authoritative assertions=${assertions}`)}
main().catch(e=>{console.error(e);process.exitCode=1})
